// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var Link = { };

var hover = (function(str) {
  if (___loader) {
    ___loader.hovering(str)
  }
});

export {
  Link ,
  hover ,
  
}
/* No side effect */
